---
title: "codeBook"
author: "Kevin Gilds"
date: "Friday, February 20, 2015"
output: html_document
---

### Girl Survey Variables

1.  **Response ID:** Alpha Numeric Code that uniquely identifies a response

2.  **ResponseSet:** Unused variable established by Qualtrics. 

3.  **StartDate:** Date the data entry started for a particular response.

4.  **EndDate:** Date the data entry was completed for a particular response.

5.  **Finished:** Identifies whethter the data entry was completed.

6.  **hr.sum:** The sum of the score obtained from the  healthy relationship questions 

7.  **hr.avg:** The average of the score obtained from healhy relationships questions.

8.  **hr.stddev:** The standard deviation of the score obtained from healthy relationships questions.

9.  **hr.disualify.sum:** The sum of the disqualification score for healthy relationship questions.

10. **Disqualify.Outcome.6.weightedAvg:** The average of the disqualification score for healthy relationship questions

11. **Disqualify.Outcome.6.weightedStdDev:** The standard deviation of the disqualification score for healthy relationship questions.

12. **ae.sum:** The sum of the score obtained from the academic engagement questions.

13. **ae.avg:** The average score obtained from the academic engagement questions.

14. **ae.stddev:** The standard deviation obtained from the academic engagement questions.

15. **am.sum:** The sum of the scores obtained from the academic mastery questions.

16.  **am.avg:** The average of the score obtained from the academic mastery questions.

17. **am.stddev:** The standard deviation obtained from the academic mastery questions

18. **am.disqualify.sum:** The sum of the scores of disqualification respones to academic mastery questions.

19. **Academic.Engagement.Disqualify.weightedAvg:** The average of the disqalification points from the academic engagement questions.

20. **Academic.Engagement.Disqualify.weihtedStdDev:** The standard devidation of the disqualification score from the academic engagement questions.

21. **ae.disquaalify.sum:** The sum of the disqualification scores obtained from academic engagement questions.

22. **Disqualify.Academic.Mastery.weightedAvg:**  The average of the disqualification scores obtained from academic mastery questions.

23. **Disqualify.Academic.Mastery.weightedStdDev:** The standard deviation of the disqualification scores obtained from the academic mastery questions.

24. **Council:** The Girl Scout Council that is delivering the service and entering the data.

25. **girlCode:** The unique identification number assigned to students in the Get REAL! program

26. **school:** The site or school where the program is delivered.

27. **Grade:** The grade of the student.

28. **Time:** Time denotes the point of the program when the student complete the survey. Pre and Post

29. **In program Last Year:** Did the student particpate in the program last year is o the survey. 

30. **iamMotivatedToGraduateHighSchool:** Question measures motivation to complete high school 

31. **iReadBooksforFun:** Question measures student's attitude towards reading.

32. **ireallyLikeWhoIam:** Question measures self worth.

33. **.....ImproveMySkillsThisYear:** Question measures motivation to improve skills

-------
    
    Survey question: It's important to me that I improve my skills this year in school
    Answer Choices:                   Points
    Strongly Agree                  = 6
    Agree                           = 4.8
    Slighly Agree                   = 3.6
    Disagree a little               = 2.4
    Disagree                        = 1.2
    Disagree a lot                  = 0
    Don't know/Don't want to say    = 0


34. **....UnderstandMyClassWork:** Question measures academic mastery skill.

--------
    
    Survey question: It's important to me that I really understand my class work
    Answer Choices:                   Points
    Strongly Agree                  = 6
    Agree                           = 4.8
    Slighly Agree                   = 3.6
    Disagree a little               = 2.4
    Disagree                        = 1.2
    Disagree a lot                  = 0
    Don't know/Don't want to say    = 0


35. **learningatSchoolIsImportantToMe:**  Question measures academic mastery life skill.

------
    
    Survey Question: Learning at school is important to me
    Answer Choices:                   Points
    Strongly Agree                  = 6
    Agree                           = 4.8
    Slighly Agree                   = 3.6
    Disagree a little               = 2.4
    Disagree                        = 1.2
    Disagree a lot                  = 0
    Don't know/Don't want to say    = 0


36. **oneofMyGoalistolearn:**  Question measures academic mastery life skill.

----
    
    Survey Question: One of my goals in school is to learn as much as I can
    Answer Choices:                   Points
    Strongly Agree                  = 6
    Agree                           = 4.8
    Slighly Agree                   = 3.6
    Disagree a little               = 2.4
    Disagree                        = 1.2
    Disagree a lot                  = 0
    Don't know/Don't want to say    = 0 

37. **...willHelpMeLaterInLife:** Question measures academic mastery life skill.

---
    
    Survey Question: The things I am learning in school will help me later in life
    Answer Choices:                   Points
    Strongly Agree                  = 6
    Agree                           = 4.8
    Slighly Agree                   = 3.6
    Disagree a little               = 2.4
    Disagree                        = 1.2
    Disagree a lot                  = 0
    Don't know/Don't want to say    = 0



38. **IfIHaveASeriousProblem:** Question measures healthy relationshisp life skill.

----

    Survey Question: If I have a serious problem, I have people to talk with
    Answer Choices:                   Points
    Strongly Agree                  = 6
    Agree                           = 4.8
    Slighly Agree                   = 3.6
    Disagree a little               = 2.4
    Disagree                        = 1.2
    Disagree a lot                  = 0
    Don't know/Don't want to say    = 0


39. **inAnyRelationshiporNotIMakeitClear:** Question measures healthy relationship life skills. ''

----

    Survey Question: In any relationship - romantic or not - I make it clear when I
    Answer Choices:                   Points
    A lot like me                   = 6
    A little like me                = 4
    Not much like me                = 2
    Not at all like me              = 2.4
    Don't know/Don't want to say    = 0
    

40. **iTalkwithMyTeacherBeforeorAfter:** Question measures academic engagement

----

    Survey Question: I talk with my teachers before or after school, or during lunch about my assignments.
    Answer Choices:                   Points
    Always                          = 6
    A lot of the time               = 4.5
    Sometime                        = 3
    Hardly Ever                     = 1.5
    Never                           = 0
    Don't know/Don't want to say    = 0
    Don't know/Don't want to say    = 

41. **iHandinMyAssignmentsOnTime:** Question measures acadenic engagement

----

    Survey Question: I hand in my assignments on time
    Answer Choices:                   Points
    Always                          = 6
    A lot of the time               = 4.5
    Sometime                        = 3
    Hardly Ever                     = 1.5
    Never                           = 0
    Don't know/Don't want to say    = 0
    Don't know/Don't want to say    = 0


42. **iFinishMyHomeworkEvenIfItisBoring:** Question measures academic engagement

----

    Survey Question: I finish my homework even if it is boring
    Answer Choices:                   Points
    Always                          = 6
    A lot of the time               = 4.5
    Sometime                        = 3
    Hardly Ever                     = 1.5
    Never                           = 0
    Don't know/Don't want to say    = 0
    Don't know/Don't want to say    = 0




43. **ifICantUnderstandMySchoolatFirstI...:** Question measures academic engagement

----

    Survey Question: If I can't understand my schoolwork at first, I keep trying until I do understand it.
    Answer Choices:                   Points
    Always                          = 6
    A lot of the time               = 4.5
    Sometime                        = 3
    Hardly Ever                     = 1.5
    Never                           = 0
    Don't know/Don't want to say    = 0
    Don't know/Don't want to say    = 0




44. **iLetPeopleKnowIfTheyHurtMyFeelings:**  Question measures healthy relationship skill

----

    Survey Question: I let people know if they have hurt my feelings
    Answer Choices:                   Points
    Always                          = 6
    A lot of the time               = 4.5
    Sometime                        = 3
    Hardly Ever                     = 1.5
    Never                           = 0
    Don't know/Don't want to say    = 0
    Don't know/Don't want to say    = 0



45. **iLetMyFriendsKnowWhenIThinkTheyAreGoodAtSomething:** Question measures healthy relationship skill

----

    Survey Question: I let my friends know when I think they are good at something
    Answer Choices:                   Points
    Always                          = 6
    A lot of the time               = 4.5
    Sometime                        = 3
    Hardly Ever                     = 1.5
    Never                           = 0
    Don't know/Don't want to say    = 0
    

46. **ILearnedFromTheBooksWeReadThisYear:** Did the student feel they learned from the books they read this year. 

-------
    
    Survey question: I learned from the books we read this year.
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree                   
    Disagree a little               
    Disagree                        
    Disagree a lot                  
    Don't know/Don't want to say    


47. **myReadingSkillsImprovedThisYear:** This question is an attributional question about the value of the program

----

    Survey question: My reading skills improved because of my participation in the Get Real Program.
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree                   
    Disagree a little               
    Disagree                        
    Disagree a lot                  
    Don't know/Don't want to say    



48. **EstablishedPositiveRelationship............................:** This question is an attributaional question about the value of the program. Can help cross validate healthy relationship skills or support it.

----

    Survey question: I established a positive relationship with my mentor in the  Get Real program.
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree                   
    Disagree a little               
    Disagree                        
    Disagree a lot                  
    Don't know/Don't want to say    


49. **HelpmeRecognizeThingsIDoWell** Attirubtional question about the value of the program in supporting self-worth

----

    Survey question: The Get Real Program helped me recognize the things I am capable of doing well.
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree                   
    Disagree a little               
    Disagree                        
    Disagree a lot                  
    Don't know/Don't want to say    


50. **WhatDidYouLearnThisYear:** Comment narrative questions. 

---

    Survey Question: What did you learn this year. 





### Parent Survey Variables


1. **ResponseID** Alpha Numeric Code that uniquely identifies a response

2. **ResponseSet** Unused variable established by Qualtrics. 

3. **StartDate**  Date the data entry started for a particular response.

4. **EndDate**  Date the data entry was completed for a particular response

5. **Finished**  Identifies whethter the data entry was completed.

6. **hr.sum** The sum of the score obtained from the  healthy relationship questions 

7. **hr.avg** The average of the score obtained from the healthy relationship questions

8. **hr.stddev** The standared deviation of the score obtained from the healthy relationship questions. 

9. **am.sum** The sum of the score obtained from the academic mastery questions.

10. **am.avg** The average of the score obtained from questions that measure academic mastery.

11. **am.stddev** The standard deviation of the score obtained from the questions that measure academic mastery.

12. **ae.sum**  The sum of the score obtained from the academic engagement questions. 

13. **ae.avg** The average of the score obtained from the academic engagement questions.

14. **ae.stddev** The standard deviatioin of the score obained from the academic engagement questions.

15. **Category.4.sum**

16. **Category.4.weightedAvg**

17. **Category.4.weightedStdDev**

18. **council**  The Girl Scout Council that is providing service to the student.

19. **girlCode** The unique identification number for students partipcating the program.

20. **schoolName** The name of the school where the student participates in the program.

21. **Time**  Identifies the time of the survey: Pre/Post

22. **graduate** This question inquires from the parent if they believe the studen is motivated to graduate high school.

----

    Survey question: She is motivated to graduate high school.
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree              
    

23. **sheHasSelfConfidnce** This question inquires from the parent if they believe the student has self confidence

----

    Survey question: She has self-confidence.
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree         

24. **goodAttitudeAboutSchool** This question inquires from the parent if they believe the student has a good attitude toward school. (Academic Mastery)

---

    Survey question: She has a good attiude about school
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree      

25. **readBooksForFun**  This question inquires from the parent if the student reads books for fun. The hope is that this changes from pre to post. 

---

    Survey question: She reads books for fun. 
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree    

26. **positiveRelationships** This question inquires from the parent if the student establishes positive relationships with peers. (Healthy Relationships)

---

    Survey question: She develops postive relationships with her classmaters
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree    

27. **homeworkWithoutSuprvision** This question inquires from the parent if the student completes homework without being told to do so.

---

    Survey question: She works on her homework without supervision. 
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree    

28. **helpedMyDaughterGainConfidenceInHerAbilities** This is an attributional question that assess from the parent if the student gained confidence in her abilities fromt the Get REAL! program.

---

    Survey question: The Get REAL! Program helped my daughter gain confidence in her abilities
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree 

29. **helpedMyDaughterAchieveSuccessInSchool** This is an attributional question that assess from the parent if they beleive the Get REAL! program helped their daughter achieve success in school. 

---

    Survey question: The Get REAL! program helped my daughter achieve success in school. 
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree 

30. **helpedEstablishPositiveRelationshipsWithHerClassmates** This is an attributional question that assess from the parent if they beleive the Get REAL! program help their daughter establish positive relationships. 

---

    Survey question: The Get REAL! program helpd her establish postive relationships with her classmaters. 
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree 

31. **helpdYourDaughterAchieveSuccessInSchool** Narrative question that asks the parents to state how the Get REAL! program help their daughter achieve success in school.

----

    Survey Question: How has the Get REAL! program helpd your daughter achieve success in school.

    Narrative





32. **ImproveTheGetRealProgam**  Narrative question that ass parent to provide feedback on the Get REAL program could be improved.

----

    Survey Question: What could be done to improve the Get REAL! program. 

    Narrative. 


### Teacher Survey Variables


1. **ResponseID** Alpha Numeric Code that uniquely identifies a response

2. **ResponseSet** Unused variable established by Qualtrics. 

3. **StartDate**  Date the data entry started for a particular response.

4. **EndDate**  Date the data entry was completed for a particular response

5. **Finished**  Identifies whethter the data entry was completed.

6. **council**  The Girl Scout Council that is providing service to the student.

7. **girlCode** The unique identification number for students partipcating the program.

8. **schoolName** The name of the school where the student participates in the program.

9. **Time**  Identifies the time of the survey: Pre/Post

10. **MotivatedToGraduateHighSchool** This question inquires from the teacher if they believe the student is motivated to graduate high school.

----

    Survey question: She is motivated to graduate high school.
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree              
    

11.  **hasSelfConfidence** This question inquires from the student's teacher if they believe the student has self confidence

----

    Survey question: She has self-confidence.
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree         


12. **goodAttitudeAboutSchool**  This question inquries from the student's teacher if they think the student has a good attitude about school. 

Survey question: She has a good attitude about school
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree     

13. **isInterestedInReading** This question inquires from the student's teacher, if the they think the student is interested in reading. 

Survey question: She is interested in reading
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree     

14. **postivelyParticipatedInClass**  Variable measures how the student particpates in class. 

Survey question: She positively participates in class
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree


15. **completesHomeworkGivenToHer** variable measures if the student completes the homework given to her from the perspective of the student's teacher.

Survey question: She completes the homework given to her. 
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree

16. **hasDevelopedPostiveRelationshipsWithHerClassmates** variable measures if the student has developed postive releationships from the perspective of the teacher. 

Survey question: She has developed positive relationships with her classmates 
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree

17. **helpedHerIncreasedHerSelfConfidence** varialbe is a post-survey that measures if the Get REAL! program has helped their daughter increase confience from the teacher's perspective. 


Survey question: The Get REAL! program helped her increase her self-confience
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree


18. **helpedHerAchieveSucessInSchool** is a post survey variable that measures if  the Get REAL! Program helped the student achieve success in school from the teacher's perspective. 

Survey question: The Get REAL! program helped her achieve success in school. 
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree


19. **helpedHerDevelopPostiveRelationship** is a post survey variable that measures if the Get REAL! Program helped the student develop positive releationships at school from the perspective of the school.

Survey question: The Get REAL! program helped her develop positive relationships at school. 
    Answer Choices:                   
    Strongly Agree                  
    Agree                           
    Slighly Agree
    Neither Agree/Disagree
    Slightly Disagree
    Disagree
    Strongly Disagree


20. **benefitsFromParticipating** is a post survey variable that is an open ended question that teachers can write how the program has benefited their students.

21. **whatCouldBeDoneToImproveTheProgram** is a post survey variable that is an open ended question that teachers can express how the program could be improved. 